tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "automake"
brew "python"
brew "ctop"
brew "gmp"
brew "gcc"
brew "libpq"
brew "python@2"
brew "libtool"
brew "qt", link: true
brew "gdal"
brew "git"
brew "gnupg"
brew "htop"
brew "pinentry-mac"
brew "postgresql@9.5", link: true
brew "ruby-build"
brew "rbenv"
brew "ruby", link: true
brew "shellcheck"
brew "tree"
brew "wget"
brew "yarn"
cask "ngrok"
