tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "automake"
brew "bash-completion"
brew "bat"
brew "python"
brew "ctop"
brew "zeromq", args: ["HEAD"]
brew "czmq", args: ["HEAD"]
brew "duti"
brew "gmp"
brew "gcc"
brew "python@3.8"
brew "hdf5"
brew "proj"
brew "libgeotiff"
brew "libpq"
brew "libspatialite"
brew "libtool"
brew "netcdf"
brew "openblas"
brew "numpy"
brew "qt", link: true
brew "gdal"
brew "git"
brew "gnupg"
brew "htop"
brew "postgresql@9.5", link: true
brew "mapnik"
# Due Travis failed build 
# brew "mas"
brew "pinentry-mac"
brew "postgresql@9.6"
brew "ruby-build"
brew "rbenv"
brew "ruby"
brew "shellcheck"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn"
brew "zsh-completions"
cask "docker"
cask "ngrok"
cask "postico"
cask "postman"
cask "qgis"
cask "slack"
cask "sublime-text"
cask "the-unarchiver"
cask "transmission"
cask "vlc"
cask "workflowy"
cask "zeplin"
cask "zoomus"
