#!/usr/bin/env bash


# ---  bash completion  --- #

if [ -f $(brew --prefix)/etc/bash_completion ]; then
   . $(brew --prefix)/etc/bash_completion
fi


# ---  python virtualenvwrapper  --- #

if [ -f ~/.virtualenvwrapper ]; then
    . ~/.virtualenvwrapper
fi


# ---  rbenv  --- #

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"


# ---  bashrc  --- #

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi


# ---  shell_env  --- #

if [ -f ~/.shell_env ]; then
    . ~/.shell_env
fi


# ---  python_startup  --- #

if [ -f ~/.python_startup ]; then
    . ~/.python_startup
fi


# ---  nvm  --- #

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
