#!/usr/bin/env zsh

. "$HOME/.shell/.exports"
. "$HOME/.shell/.aliases"
. "$HOME/.shell/.functions"

# ---  Local variables and overrides  --- #

if [[ -f "$HOME/.shell_env_local" ]]; then
  . "$HOME/.shell_env_local"
fi
